apiVersion: v1
kind: Service
metadata:
  name: string-reverser-service
spec:
  # Using NodePort allows us to reliably expose the service using the kubectl port-forward command.
  type: NodePort
  selector:
    # This must match the 'app' label in your deployment.yaml
    app: string-reverser
  ports:
    - protocol: TCP
      # This is the port inside the Kubernetes cluster.
      port: 5000
      targetPort: 5000

